name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: filter results
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            lambda_code:
              - 'raffle.py'
      - name: deploy lambda_code
        if: steps.filter.outputs.lambda_code == 'true'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: dou-macbook-raffle
          source: raffle.py
